name: Test token pull request lable

on: [pull_request_target]

#permissions

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}