name: Container

on: push

jobs:
  node-container-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Log node version
        run: "curl http://localhost:3001/api/users"